# Generated by Django 4.0.2 on 2022-03-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 17, 9, 45, 454023), verbose_name='date published'),
        ),
    ]
