# Generated by Django 4.0.2 on 2022-03-06 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 21, 52, 33, 713553), verbose_name='date published'),
        ),
    ]
